### ISSUE TITLE
Exception in thread "main" java.io.StreamCorruptedException: invalid stream header: 4D6F7665

### ISSUE THREAD

**Issue by hatemmaihoob** [ferortega/cf4j#23]
Hi Sir
when i run the project the following error appears:
run:
Exception in thread "main" java.io.StreamCorruptedException: invalid stream header: 4D6F7665
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:806)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
	at es.upm.etsisi.cf4j.data.BenchmarkDataModels.loadRemoteDataModel(BenchmarkDataModels.java:245)
	at es.upm.etsisi.cf4j.data.BenchmarkDataModels.MovieLens100K(BenchmarkDataModels.java:35)
	at MSE_movieLens100k.main(MSE_movieLens100k.java:31)
Java Result: 1
BUILD SUCCESSFUL (total time: 0 seconds)

**Comment by ferortega** [comment]
Hi hatemmaihoob,

Thank you for reporting us the error.  We are working to solve it. The hosting that hosts the binary files containing the benchmark datamodels has changed its configuration and no longer allows downloading files via HTTP. We are working on a solution to access these files via HTTPS. We expect to release a patch this week.

**Comment by ferortega** [comment]
We have upgraded CF4J to version 2.3.0. This version should let you use BenchmarkDataModels again.
